// Session: Day 16 - Cloud Fundamentals on Azure (2026-09-15) - subtopics: IaaS/PaaS/SaaS, regions, resource groups, subscriptions, VMs, App Service, Functions, AKS, Blob/Files/Table/Queue storage and tiers, VNet, subnets, NSG, load balancer, DNS
export default [
  {
    text: "Which cloud service model gives you virtual machines whose operating system you patch and manage yourself?",
    options: ["IaaS", "PaaS", "SaaS", "Managed database"],
    answer: 0,
    complexity: "easy",
    explanation: "Infrastructure as a Service rents compute, storage and network. The provider runs the hardware, you run everything above it.",
  },
  {
    text: "In Azure, what is a resource group?",
    options: [
      "A billing account for a whole company",
      "A logical container for related resources",
      "A physical rack inside a datacentre",
      "A pool of reserved virtual machines",
    ],
    answer: 1,
    complexity: "easy",
    explanation: "Resource groups gather resources that share a lifecycle so they can be deployed, managed and deleted together.",
  },
  {
    text: "What is an Azure region?",
    options: [
      "A single physical server",
      "A spending limit on a subscription",
      "A set of datacentres in one geographic area",
      "A directory tenant for user accounts",
    ],
    answer: 2,
    complexity: "easy",
    explanation: "Choosing a region places resources near users or inside a required jurisdiction, and it affects latency and price.",
  },
  {
    text: "Which Azure storage service is designed for large unstructured files such as images, video and backups?",
    options: ["Table Storage", "Queue Storage", "Azure Files", "Blob Storage"],
    answer: 3,
    complexity: "easy",
    explanation: "Blob Storage holds arbitrary objects of almost any size in containers and is the default choice for unstructured data.",
  },
  {
    text: "What does Azure App Service provide?",
    options: [
      "Managed hosting for web apps and APIs",
      "A managed Kubernetes control plane",
      "A relational database engine",
      "A gateway between two virtual networks",
    ],
    answer: 0,
    complexity: "easy",
    explanation: "App Service is a PaaS platform: you deploy the application and Azure runs the servers, patching and scaling.",
  },
  {
    text: "What is Azure Functions best suited for?",
    options: [
      "Running a full desktop operating system",
      "Short event-driven code with no servers to manage",
      "Hosting a private container registry",
      "Storing terabytes of archived blobs",
    ],
    answer: 1,
    complexity: "easy",
    explanation: "Functions runs small pieces of code in response to triggers such as HTTP calls, timers or queue messages.",
  },
  {
    text: "Within an Azure virtual network, what is a subnet used for?",
    options: [
      "Encrypting traffic between regions",
      "Assigning public DNS names to hosts",
      "Splitting the address space into smaller ranges",
      "Billing network traffic per department",
    ],
    answer: 2,
    complexity: "easy",
    explanation: "Subnets divide the VNet address space so resources can be grouped and controlled separately, usually with their own NSG.",
  },
  {
    text: "What does a network security group (NSG) do?",
    options: [
      "Scrubs volumetric DDoS attacks",
      "Issues TLS certificates to virtual machines",
      "Spreads traffic across virtual machines",
      "Allows or denies traffic using rules",
    ],
    answer: 3,
    complexity: "easy",
    explanation: "An NSG is a stateful filter of allow and deny rules matched on source, destination, port and protocol.",
  },
  {
    text: "What role does an Azure subscription play?",
    options: [
      "A billing and access boundary for resources",
      "A single virtual network",
      "A grouping of Azure regions",
      "An identity assigned to an application",
    ],
    answer: 0,
    complexity: "medium",
    explanation: "Resources are created inside a subscription, which carries the invoice, the quotas and a top-level scope for role assignments.",
  },
  {
    text: "Backups are read once or twice a year, hours of retrieval delay are fine, and storage cost must be lowest. Which blob tier?",
    options: ["Hot", "Archive", "Cool", "Premium"],
    answer: 1,
    complexity: "medium",
    explanation: "Archive has the cheapest storage and the highest retrieval cost and latency, since blobs must be rehydrated before reading.",
  },
  {
    text: "Which Azure storage service exposes an SMB file share that virtual machines can mount as a drive?",
    options: ["Blob Storage", "Queue Storage", "Azure Files", "Table Storage"],
    answer: 2,
    complexity: "medium",
    explanation: "Azure Files serves fully managed shares over SMB or NFS, so lift-and-shift apps keep using a normal file path.",
  },
  {
    text: "What is Azure Queue Storage typically used for?",
    options: [
      "Serving a static website",
      "Storing relational data with joins",
      "Mounting a shared drive on Windows",
      "Decoupling components with async messages",
    ],
    answer: 3,
    complexity: "medium",
    explanation: "A queue buffers work between a producer and a consumer, letting each scale and fail independently.",
  },
  {
    text: "When is AKS a better fit than App Service?",
    options: [
      "When you must orchestrate many containers",
      "When you want the least infrastructure to run",
      "When the app is one static HTML page",
      "When code only needs to run on a timer",
    ],
    answer: 0,
    complexity: "medium",
    explanation: "AKS gives full Kubernetes orchestration for multi-container systems, at the cost of managing clusters, nodes and manifests.",
  },
  {
    text: "What does an Azure load balancer do?",
    options: [
      "Caches static content close to users",
      "Distributes traffic across healthy backends",
      "Resolves domain names to IP addresses",
      "Rewrites HTTP headers on each request",
    ],
    answer: 1,
    complexity: "medium",
    explanation: "It spreads connections over a backend pool and uses health probes to stop sending traffic to failing instances.",
  },
  {
    text: "Which Azure service hosts the records that map a custom domain name to a resource address?",
    options: ["Azure Firewall", "Azure Monitor", "Azure DNS", "Azure Bastion"],
    answer: 2,
    complexity: "medium",
    explanation: "Azure DNS hosts zones and record sets, so you can point a company domain at App Service, a load balancer or storage.",
  },
  {
    text: "Two subnets sit in the same virtual network and their VMs need to talk to each other. What is required by default?",
    options: [
      "A VNet peering link",
      "A site-to-site VPN gateway",
      "A public IP on each virtual machine",
      "Nothing; they can already route to each other",
    ],
    answer: 3,
    complexity: "medium",
    explanation: "Azure routes between subnets of a VNet automatically. Peering is only needed to join separate virtual networks.",
  },
  {
    text: "Why do teams spread a workload across several availability zones in a region?",
    options: [
      "To survive a datacentre failure in that region",
      "To lower the hourly price of virtual machines",
      "To avoid needing a resource group",
      "To obtain a static public IP address",
    ],
    answer: 0,
    complexity: "medium",
    explanation: "Zones are physically separate facilities with independent power and cooling, so a single site outage does not take the app down.",
  },
  {
    text: "Under the shared responsibility model for IaaS virtual machines, who is responsible for patching the guest operating system?",
    options: [
      "Microsoft, automatically for every VM",
      "The customer",
      "The datacentre operator for the region",
      "Nobody; the OS image is immutable",
    ],
    answer: 1,
    complexity: "medium",
    explanation: "With IaaS Microsoft secures the physical layer and hypervisor, while the customer owns the guest OS, applications and data.",
  },
  {
    text: "An App Service web app must reach a database that has no public endpoint. Which approach fits?",
    options: [
      "Give the web app a public IP address",
      "Open the database firewall to 0.0.0.0/0",
      "Use VNet integration and a private endpoint",
      "Copy the database into Blob Storage",
    ],
    answer: 2,
    complexity: "hard",
    explanation: "VNet integration puts the app's outbound traffic inside the network, and a private endpoint gives the database a private IP there.",
  },
  {
    text: "You delete a resource group that still contains a virtual machine, a disk and a public IP. What happens?",
    options: [
      "They move to a default resource group",
      "They keep running but stop being billed",
      "They are archived for ninety days",
      "All of the contained resources are deleted",
    ],
    answer: 3,
    complexity: "hard",
    explanation: "Deleting a resource group deletes everything inside it. Use resource locks to protect groups that must not be removed.",
  },
  {
    text: "A job runs for two minutes when a queue message arrives, a few times an hour. Which compute option is most cost-effective?",
    options: [
      "Azure Functions on a consumption plan",
      "A dedicated VM left running all day",
      "An AKS cluster with three nodes",
      "An App Service isolated plan",
    ],
    answer: 0,
    complexity: "hard",
    explanation: "The consumption plan bills per execution and runtime, so idle time costs nothing. The other options pay for reserved capacity.",
  },
  {
    text: "An NSG has an allow rule at priority 300 and a deny rule at priority 200 that both match the same inbound traffic. What happens?",
    options: [
      "The traffic is allowed, since allow wins",
      "The traffic is denied, since 200 is evaluated first",
      "The rules cancel and the packet is dropped",
      "Both rules are ignored as conflicting",
    ],
    answer: 1,
    complexity: "hard",
    explanation: "NSG rules are processed in ascending priority order and the first match wins, so the lower number takes effect.",
  },
  {
    text: "Log blobs older than thirty days must cost less to keep, without changing any application code. What is the cleanest option?",
    options: [
      "Delete the storage account each month",
      "Copy the blobs onto a VM disk by script",
      "Apply a lifecycle management policy",
      "Move the account to a cheaper region",
    ],
    answer: 2,
    complexity: "hard",
    explanation: "A lifecycle policy moves blobs to Cool or Archive, or deletes them, on a rule based on age, entirely outside the application.",
  },
  {
    text: "A virtual machine must read from Blob Storage without any credential stored on the machine. What should it use?",
    options: [
      "A shared account key in an environment variable",
      "A SAS token committed to the repository",
      "A connection string baked into the VM image",
      "A managed identity with a storage role",
    ],
    answer: 3,
    complexity: "hard",
    explanation: "A managed identity lets Azure issue tokens to the VM itself, so access is granted by role assignment with no secret to leak or rotate.",
  },
];
