// Quiz sessions taken from the training schedule (weeks 3–4). Flex Fridays, the capstone
// week and the assessment day have no quiz, so they are not listed. Dates are 2026.
export default [
  {
    key: 'day09-python', dayNo: 9, date: '2026-09-03', week: 'Week-3',
    module: 'Programming', title: 'Python',
    subtopics: 'Syntax, OOP, File Handling, API Calls, Automation Scripts, JSON Processing',
    trainers: ['Subachandran G', 'Priyadith'],
    slidesKey: 'day09-python',
  },
  {
    key: 'day11-spring-boot', dayNo: 11, date: '2026-09-07', week: 'Week-3',
    module: 'Backend', title: 'Spring Boot',
    subtopics: 'Dependency Injection, Controllers, Services, API Gateway, Resilience',
    trainers: ['Syed Suhail', 'Saurav Sanyal'],
    trainerEmails: ['syed.suhail@ferguson.com', 'saurav.sanyal@ferguson.com', 'mahesh.j@ferguson.com'],
    slidesKey: 'day11-spring-boot',
  },
  {
    key: 'day12-sql-mongodb', dayNo: 12, date: '2026-09-08', week: 'Week-3',
    module: 'Database', title: 'SQL (Azure SQL) & MongoDB',
    subtopics: 'SQL, Joins, Stored Procedures, NoSQL Concepts, Collections, CRUD',
    trainers: ['Dushanth (SQL)', 'Vishnu C (Mongo DB)'],
    trainerEmails: ['mahesh.j@ferguson.com', 'dushantha.sb@ferguson.com', 'vishnu.chaturvedi@ferguson.com'],
    slidesKey: 'day12-sql-mongodb',
  },
  {
    key: 'day13-frontend', dayNo: 13, date: '2026-09-09', week: 'Week-3',
    module: 'Frontend', title: 'HTML, CSS, JavaScript & React',
    subtopics: 'Frontend Fundamentals, Components, State, Props, Hooks, Routing',
    trainers: ['Kaushik C (JS)', 'Prakash (React, HTML, CSS)'],
    trainerEmails: ['prakash.ubs@ferguson.com', 'kaushik.kaushik@ferguson.com'],
    slidesKey: 'day13-frontend',
  },
  {
    key: 'day14-devops-etl', dayNo: 14, date: '2026-09-10', week: 'Week-3',
    module: 'DevOps & ETL', title: 'DevOps & ETL (Databricks)',
    subtopics: 'Git, Jenkins, Docker, Kubernetes, CI/CD Pipeline, Databricks',
    trainers: ['Ravi Chabria (DevOps)', 'Santoshini (ETL)'],
    trainerEmails: ['ravi.chabria@ferguson.com', 'santoshini.panda@ferguson.com'],
    slidesKey: 'day14-devops-etl',
  },
  {
    key: 'day16-cloud', dayNo: 16, date: '2026-09-15', week: 'Week-4',
    module: 'Cloud', title: 'Cloud Fundamentals',
    subtopics: 'Azure Cloud Overview, Compute, Storage, Networking',
    trainers: ['Ashutosh Singh'],
    trainerEmails: ['ashutosh.singh@ferguson.com'],
  },
  {
    key: 'day17-domain-erp', dayNo: 17, date: '2026-09-16', week: 'Week-4',
    module: 'Domain / ERP', title: 'Salesforce, Trilogie, SupplyChain',
    subtopics: 'Sales, Service, Commerce, Trilogie, Logility, HighJump, Inventory',
    trainers: ['Vidisha / Tejas (Trilogie)', 'Savitha (Supply Chain)', 'Arpitha (Salesforce)'],
    trainerEmails: ['arpitha.jh@ferguson.com', 'vidisha.bhat@ferguson.com', 'savita.dodamani@ferguson.com'],
  },
  {
    key: 'day18-integration-ai', dayNo: 18, date: '2026-09-17', week: 'Week-4',
    module: 'Integration / AI', title: 'Enterprise Integration / AI Assistance',
    subtopics: 'REST, SOAP, APIGEE, Kafka, OAuth/JWT, GitHub Copilot, Gemini, Prompt Engineering',
    trainers: ['Kranthi Kumar (Integration)', 'Tharun Kumar (AI)'],
    trainerEmails: ['kranthi.kumar@ferguson.com', 'tharunkumar.kumart@ferguson.com'],
    slidesKey: 'day18-integration-ai',
  },
];
